---
#os: linux
#dist: jessie
sudo: required
services: docker

env:
  playbook: test.yml
  matrix:
    # package: build packages for distribution $DIST
    - DIST="debian:jessie"
    - DIST="debian:stretch"

before_install:
#  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew"  docker-engine

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
#  - ansible-galaxy install -r test/requirements.yml -p test/roles/

script:
  - cd test && sudo ansible-playbook -i inventory main.yml
#  - cd test && sudo ansible-playbook -i inventory -e "provision_docker_privileged=true" main.yml

#notifications:
  # notify ansible galaxy of test results
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
