
---

- name: Install required package
  apt: pkg={{ item }} state=latest
  with_items:
      - ntp
      - ntp-doc
  notify:
      - start ntp
  tags: [ 'package', 'ntp' ]

- name: Create and install the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes
  notify:
      - restart ntp
  tags: [ 'configuration', 'package', 'ntp' ]

